### ISSUE TITLE
Misunderstand of configuration

### ISSUE THREAD

**Issue by abneb** [Axlfc/UE5-python#1]
Hey,
Sorry about my doubt. I'm a begginer in programming and contributing here. So, I couldn't figure out how to paste my keys. It has a .env in twitBot. But when I paste OPENAI.API_KEY = os.environ there it doesn't work. l already try to create another .env file in chatBot and in the root directory and both failed too.

**Comment by Axlfc** [comment]
Hello Carlos,
You have to create a new '.env' file inside the chatBot folder containing a variable named OPENAI_API_KEY and its value from what API Key you have generated in [openai webpage](https://beta.openai.com/account/api-keys). I had to delete the .env file from the folder bc I'm making changes to this repository and you must never upload your API key of anything anywhere of a git repository.

If you want, an easier way to install chatGPT on your terminal, install chatGPT using Linux-Auto-Customizer.

`sudo apt-get install -y git python3`
`git clone https://github.com/Axlfc/Linux-Auto-Customizer`
`cd Linux-Auto-Customizer`
`git checkout chatGPT_feature`
`bash src/core/install.sh -v -o chatGPT`
`bash`

You will need to do exactly the same as you are asking me here. To go to the folder, (in the case you install it with customizer that would be ~/.customizer/bin/chatGPT/Content/Python/chatBot ) and create a new file named '.env' and set a variable named OPENAI_API_KEY and paste the value of your API key like:

`OPENAI_API_KEY=your_API_key_value*blablablah`

Save and close the file ~/.customizer/bin/chatGPT/Content/Python/chatBot/.env

# An example one-liner command to do exactly that:
Change 'your_API_key_value' to the one you got from openai webpage before running the next command:

`echo "OPENAI_API_KEY=your_API_key_value" > ~/.customizer/bin/chatGPT/Content/Python/chatBot/.env`

Next you are ready to go.

If you installed it with customizer, you would be running it by a simple terminal command typing **chatGPT** in the console and without making any explicit call to python3. Much more clean & comfy.


Let me know if my answer helped you so I can close this issue!!

Cheers,
Axel

**Comment by Axlfc** [comment]
Guessing this issue is closed

**Comment by abneb** [comment]
Hey Axlfc!
Sorry for my delay. I follow your instructions and everything works just fine. 
Look for testing right now. 
Thanks man
